services:
  app:
    build: .
    container_name: connecteamed-be-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - APP_S3_ACCESS_KEY=${APP_S3_ACCESS_KEY}
      - APP_S3_SECRET_KEY=${APP_S3_SECRET_KEY}
      - APP_S3_BUCKET=${APP_S3_BUCKET}
      - APP_S3_REGION=${APP_S3_REGION}
