services:
  db:
    image: postgres:16
    container_name: connected-be-db
    environment:
      POSTGRES_DB: connected
      POSTGRES_USER: connected
      POSTGRES_PASSWORD: connected
    ports:
      - "5432:5432"
    volumes:
      - connected-be-db:/var/lib/postgresql/data

volumes:
  connected-be-db:
