services:
  db:
    image: postgres:16
    container_name: connecteamed-be-db
    environment:
      POSTGRES_DB: connecteamed
      POSTGRES_USER: connecteamed
      POSTGRES_PASSWORD: connecteamed
    ports:
      - "5432:5432"
    volumes:
      - connecteamed-be-db:/var/lib/postgresql/data

volumes:
  connecteamed-be-db:
