services:
  db:
    image: postgres:16
    container_name: connecteamed-be-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - connecteamed-be-db:/var/lib/postgresql/data
    networks:
      - connecteamed-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: connecteamed-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - connecteamed-network
    depends_on:
      - db

  app:
    ports:
      - "8080:8080"
    build: .
    container_name: connecteamed-be-app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - APP_S3_ACCESS_KEY=${APP_S3_ACCESS_KEY}
      - APP_S3_SECRET_KEY=${APP_S3_SECRET_KEY}
      - APP_S3_BUCKET=${APP_S3_BUCKET}
      - APP_S3_REGION=${APP_S3_REGION}
    networks:
      - connecteamed-network
    depends_on:
      - db

networks:
  connecteamed-network:
    name: ${DOCKER_NETWORK:-connecteamed-network}
    driver: bridge

volumes:
  connecteamed-be-db:
