spring:
  application:
    name: connecteamed-be

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/connecteamed}
    username: ${DB_USERNAME:connecteamed}
    password: ${DB_PASSWORD:connecteamed}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    open-in-view: false

server:
  port: 8080

app:
  s3:
    region: ${APP_S3_REGION:ap-northeast-2}
    bucket: ${APP_S3_BUCKET}
    access-key: ${APP_S3_ACCESS_KEY}
    secret-key: ${APP_S3_SECRET_KEY}
