spring:
  application:
    name: connected-be

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/connected}
    username: ${DB_USERNAME:connected}
    password: ${DB_PASSWORD:connected}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    open-in-view: false

server:
  port: 8080
