spring:
  application:
    name: connecteamed-be

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/connecteamed}
    username: ${DB_USERNAME:connecteamed}
    password: ${DB_PASSWORD:connecteamed}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  port: 8080
