spring:
  application:
    name: connecteamed-be

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/connecteamed}
    username: ${DB_USERNAME:connecteamed}
    password: ${DB_PASSWORD:connecteamed}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    open-in-view: false

jwt:
  token:
    secretKey: ${JWT_SECRET_KEY}
    expiration:
      access: 14400000
      refresh: 1209600000


springdoc:
  swagger-ui:
    # Swagger UI 접속 경로를 /docs로 변경
    # http://localhost:8080/docs 로 접속
    path: /docs

server:
  port: 8080
